### PR TITLE
changing /info http method to GET

### PR DESCRIPTION
**Pull request by nmonterroso**
@Wikia/services-team 
https://wikia-inc.atlassian.net/browse/SERVICES-462

We changed the HTTP method of `/info` to `POST`, but the api gateway and MediaWiki currently use `GET`, and that also seems more appropriate, so changing this back to `GET /info`

### CODE REVIEW

**Comment by ArturKlajnerok** [comment]
Seems that e2e test for token invalidation are failing.

**Comment by nmonterroso** [comment]
@ArturKlajnerok yah i'm looking.

**Comment by nmonterroso** [comment]
looks like `code` is no longer being accepted as a form param in the `get` request, which seems correct, but I wonder why it was working before O.o

**Comment by ArturKlajnerok** [comment]
Lgtm :+1:

**Pull request merged**
