### PR TITLE
[SERVICES-615] Added underscore to illegal username characters

### PR DESCRIPTION
**Pull request by ArturKlajnerok**
/cc @Wikia/services-team @owend

### CODE REVIEW

**Comment by nmonterroso** [comment]
Is it that usernames are blocked? I thought I could ask for username `hi_there`, but MW would transform it to `hi there`?

**Comment by ArturKlajnerok** [comment]
@nmonterroso I've double check that.

**Comment by sqreek** [comment]
LGTM

**Comment by ArturKlajnerok** [comment]
Ok, it seems that it's safe to block that character instead of transforming it to space.

**Pull request merged**
