### PR TITLE
SERVICES-531 Add "POST" handler to FB Connect

### PR DESCRIPTION
**Pull request by bkoval**
https://wikia-inc.atlassian.net/browse/SERVICES-531

@ArturKlajnerok @nmonterroso Since we're not sure if PUT requests and CORS work nicely in the browsers, how about we add a POST handler to FB Connect resource to ensure the requests are not blocked?

### CODE REVIEW

**Comment by kvas-damian** [comment]
LGTM

**Comment by drsnyder** [comment]
> Since we're not sure if PUT requests and CORS work nicely in the browsers, how about we add a POST handler to FB Connect resource to ensure the requests are not blocked?

We decided upon `PUT` here because the URI `/users/<user_id>/facebook_app_id/<app_id>` can and probably will be used as a stable resource for the connection whose representation provides metadata about the connection. I would rather not compromise the HTTP semantics until we know for sure that we must in order to get around CORS or some other issue.

**Comment by drsnyder** [comment]
@ArturKlajnerok is currently looking into whether or not the api-gateway is the issue. Let's see what he finds out.

**Comment by ArturKlajnerok** [comment]
Closing as we solve the CORS problem on the api-gateway level.

**Pull request closed without merging**
